
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox


#waybar
exec-once = waybar

#swaync - notifications
exec-once = swaync



#hyprsunset
exec-once = hyprsunset

#hyprlock

exec-once = hyprlock --daemon

#udiskie - auto mount drives
exec-once = udiskie --tray=false

#polkit agent polkit agent
# exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent

#clipboard
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = wl-clip-persist --clipboard regular

#wallpaper
exec-once = waypaper --restore


#KDE service cache
exec-once = kbuildsycoca6 --noincremental
