source = $HOME/.config/hypr/tokyoNightStorm.conf

$font = Inter Display
$font-nerd = RobotoMono Nerd Font Propo

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = ~/Pictures/wallpapers/wallhaven/wallhaven-e8ek18.png
    color = $background
    blur_passes = 3
    blur_size = 8
    brightness = 1

}
# Profile Picture
image {
    monitor =
    path = ~/Pictures/small-pics/gamer-cat.png
    size = 100
    border_size = 8
    border_color = rgba($foregroundRaw33)
    position = 0, 200
    halign = center
    valign = bottom
}


#user
# label {
#     monitor =
#     # text = cmd[update:1000] whoami
#     text =$USER
#     font_family = $font
#     color = rgba($foregroundRaw88)
#     position = 0, 160
#     halign = center
#     valign = bottom
# }

input-field {
    monitor =
    size = 200, 30
    outline_thickness = 4
    inner_color = rgba($foregroundRaw33)

    # outer_color = $green $sapphire 30deg
    # check_color = $red $peach 120deg
    # fail_color = $red $peach 30deg

    outer_color = rgba($foregroundRaw50)
    check_color = rgba($yellowRawff)
    fail_color = rgba($redRawff)

    font_color = rgba($foregroundRaw88)
    fade_on_empty = false
    rounding = 15

    font_family = $font-nerd
    placeholder_text =
    fail_text =

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = 󰜡
    dots_size = 0.4
    dots_spacing = 0.6

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 80
    halign = center
    valign = bottom
}



# TIME
label {
    monitor =
    text = cmd[update:1]  date +"%l:%M"
    font_size = 120
    font_family = $font black
    position = 0, -200
    halign = center
    valign = top
    color = rgba($foregroundRaw50)
}

# day
label {
    monitor =
    text = cmd[update:1] date +"%a"
    font_size = 16
    font_family = $font
    position = -150, -380
    halign = center
    valign = top
    color = rgba($foregroundRaw50)
}

#separator
label {
    monitor =
    text = 󰜡
    font_size = 14
    font_family = $font-nerd
    position = -100, -382
    halign = center
    valign = top
    color=rgba($redRawff)
}

# date
label {
    monitor =
    text = cmd[update:1] date +"%e"
    font_size = 16
    font_family = $font
    position = -50, -380
    halign = center
    valign = top
    color = rgba($foregroundRaw50)
}
#separator
label {
    monitor =
    text = 󰜡
    font_size = 14
    font_family = $font-nerd
    position = 0, -382
    halign = center
    valign = top
    color=rgba($greenRawff)
}

# month
label {
    monitor =
    text = cmd[update:1] date +"%b"
    font_size = 16
    font_family = $font
    position = 50, -380
    halign = center
    valign = top
    color = rgba($foregroundRaw50)
}
#separator
label {
    monitor =
    text = 󰜡
    font_size = 14
    font_family = $font-nerd
    position = 100, -382
    halign = center
    valign = top
    color=rgba($purpleRawff)
}
# Year
label {
    monitor =
    text = cmd[update:1] date +"%Y"
    font_size = 16
    font_family = $font
    position = 150, -380
    halign = center
    valign = top
    color = rgba($foregroundRaw50)
}
