#colors


### MONITORS ###
monitor=HDMI-A-1, 1920x1080@100.00, auto, auto

### AUTOSTART ###
source = ~/.config/hypr/autostart.conf
#cursor - catppuccin-mocha-mauve-cursors


### MY PROGRAMS ###
$terminal = kitty
$fileManager = dolphin
$menu = pkill rofi || rofi -show drun
$editor = zeditor -n
$browser = flatpak run io.github.ungoogled_software.ungoogled_chromium





### ENVIRONMENT VARIABLES ###

source = ~/.config/hypr/env.conf

### LOOK AND FEEL ###
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/animations/LimeFrenzy.conf


### INPUT ###
source = ~/.config/hypr/inputs.conf


### KEYBINDINGS ###
source = ~/.config/hypr/keybinds.conf


### WINDOWS AND WORKSPACES ###
source = ~/.config/hypr/rules.conf











dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
