$background = rgb(24283b)
$backgroundRaw = 24283b
$foreground = rgb(c0caf5)
$foregroundRaw = c0caf5
$selection = rgb(2e3c64)
$selectionRaw = 2e3c64
$comment = rgb(565f89)
$commentRaw = 565f89
$red = rgb(f7768e)
$redRaw = f7768e
$orange = rgb(ff9e64)
$orangeRaw = ff9e64
$yellow = rgb(e0af68)
$yellowRaw = e0af68
$green = rgb(9ece6a)
$greenRaw = 9ece6a
$purple = rgb(7aa2f7)
$purpleRaw = 7aa2f7
$cyan = rgb(2ac3de)
$cyanRaw = 2ac3de
$pink = rgb(bb9af7)
$pinkRaw = bb9af7
$accent = $purple
$accentRaw = $purpleRaw
