
# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#cusom float window rule
windowrule{
    name = float-calculator

    match:class = org.gnome.Calculator
    float = yes
}
windowrule{
    name = float-nm-config-editor

    match:class = nm-connection-editor
    float = yes
    opacity = 0.8
}
windowrule{
    name = float-overskride

    match:class = io.github.kaii_lb.Overskride
    float = yes
    opacity = 0.8
}

windowrule{
    name = kitty-opacity

    match:class = kitty
    opacity = 0.8
}
windowrule{
    name = Alacritty-opacity

    match:class = Alacritty
    opacity = 0.8
}
windowrule{
    name = volume-mixer
    match:class = org.pulseaudio.pavucontrol
    opacity = 0.8
    float = yes
}
windowrule{
    name = Picture-in-Picture
    match:title = Picture-in-Picture
    float = yes
}
windowrule{
    name = vscodium
    match:class = codium
    opacity = 0.8
}
windowrule{
    name = nemo
    match:class = nemo
    opacity = 0.8
}



# custom rules for custom window/layer blur:

layerrule = blur on, match:class kitty
layerrule = blur on, match:class wlogout

layerrule = blur on, match:class swaync-control-center
layerrule = ignore_alpha 0, match:class swaync-control-center

